import type { Metadata } from "next";
import "./globals.css";

import { plusJakartaSans } from "./lib/font";
import Header from './components/Header';
import Footer from './components/Footer';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className={`${plusJakartaSans.className} min-h-full flex flex-col bg-background-primary text-text-primary`}>
        <Header />
        <main className="flex-1">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}

