import type { Metadata } from "next";
import "./globals.css";
import { plusJakartaSans } from "./lib/font";
import Header from './components/Header/Header';
import Footer from './components/Footer';
import { ThemeProvider } from "next-themes";
import AddTaskModalProvider from "./context/AddTaskModalContext";
import TaskProvider from "./context/TaskContext";
import HeaderProvider from "./context/HeaderContext";
import TaskFilterProvider from "./context/TaskFilterContext";
//import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
      suppressHydrationWarning
    >
      
        <body className={`${plusJakartaSans.className} bg-background-primary min-h-full flex flex-col text-text-primary`}>
          {/*<Providers>*/}
            <ThemeProvider attribute="class" enableSystem defaultTheme="system">
              <TaskFilterProvider>
                <HeaderProvider>
                  <Header />
                </HeaderProvider>
                <main className="flex-1">
                  <AddTaskModalProvider>
                    <TaskProvider>
                      {children}
                    </TaskProvider>
                  </AddTaskModalProvider>
                </main>
              </TaskFilterProvider>
              <Footer />
            </ThemeProvider>
          {/*</Providers>*/}
        </body>
    </html>
  );
}

